; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = "ESLP Smart House"
description = "ESLP Smart House - ESP32-based IoT project for home automation and monitoring."
src_dir = src
build_dir = build
extra_configs = secrets.ini

[env]
build_flags = 
	-D VERSION=1.0.0
	'-D WIFI_SSID= ${secrets.wifi_ssid}'
	'-D WIFI_PASSWORD= ${secrets.wifi_pass}'
	'-D WEB_SERVER_PORT= ${secrets.web_server_port}'
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
lib_deps = 
	olikraus/U8g2@^2.36.18
	adafruit/RTClib@^2.1.4
	adafruit/DHT sensor library@^1.4.7
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.11.0

[env:esp32dev_debug]
build_type = debug
build_flags = 
	${env.build_flags}
	-D DEBUG
monitor_speed = 115200
upload_speed = 115200
monitor_port = /dev/ttyUSB1
upload_port = /dev/ttyUSB1

[env:esp32dev_release]
build_type = release
upload_port = /dev/ttyUSB1
